title:              Lior Sinai
email:              sinailior@gmail.com
description:        Musings on mathematics, coding and physics.
author:             Lior Sinai
baseurl:            ""
url:                "https://liorsinai.github.io"


# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  
highlightjs_theme: "monokai-sublime"  #https://highlightjs.org/


# Social Profiles
social:
  - name: GitHub
    icon: github  # font awesome icons
    username: LiorSinai
    url: https://github.com/LiorSinai
    
  - name: LinkedIn
    icon: linkedin
    username: lior-sinai-907191113
    url: https://www.linkedin.com/in/lior-sinai-907191113 
    
  - name: Instagram
    icon: instagram  # font awesome icons
    username: LiorSinai
    url: https://instagram.com/lior_origami
    
  - name: goodreads
    icon: goodreads-g  
    username: 61077900-lior-sinai
    url: ""
    