title:              Lior Sinai
email:              sinailior@gmail.com
description:        My website for musings on mathematics, coding and physics.
author:             Lior Sinai
baseurl:            ""
url:                "https://liorsinai.github.io"

# Social Profiles
#twitter_username:   SBootstrap
github_username:    LiorSinai
#facebook_username:  StartBootstrap
instagram_username:  lior_origami
linkedin_username: lior-sinai-907191113

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

